// ... existing setup code ...

document.getElementById('openChat').addEventListener('click', function() {
    chrome.tabs.create({url: 'chat.html'});
});
// ... other code ...

// ... rest of the original code ...
